---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  labels:
    name: elasticsearch-master
    service: elasticsearch
spec:
  selector:
    service: elasticsearch
    role: master
  # Headless
  clusterIP: None
  ports:
    - name: http
      port: 9300
