---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
    service: elasticsearch
    role: client
spec:
  selector:
    service: elasticsearch
    role: client
  # Headless
  clusterIP: None
  ports:
    - name: http
      port: 9200
